2022-03-10 07:49:53,753:DEBUG:certbot._internal.main:certbot version: 1.24.0
2022-03-10 07:49:53,753:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2022-03-10 07:49:53,753:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'credit812@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'www.onetop.n-e.kr']
2022-03-10 07:49:53,753:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-03-10 07:49:53,863:DEBUG:certbot._internal.log:Root logging level set at 30
2022-03-10 07:49:53,869:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2022-03-10 07:49:53,872:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f62834139a0>
Prep: True
2022-03-10 07:49:53,873:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f62834139a0> and installer None
2022-03-10 07:49:53,873:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2022-03-10 07:49:53,898:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/444307680', new_authzr_uri=None, terms_of_service=None), c7e9168514a39e1300ba223182501308, Meta(creation_dt=datetime.datetime(2022, 3, 10, 7, 46, 40, tzinfo=<UTC>), creation_host='f5f654c18290', register_to_eff=None))>
2022-03-10 07:49:53,899:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2022-03-10 07:49:53,900:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2022-03-10 07:49:54,424:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2022-03-10 07:49:54,425:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 10 Mar 2022 07:49:55 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "cERcMfPsDww": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2022-03-10 07:49:54,463:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer <certbot._internal.cli.cli_utils._Default object at 0x7f628342a700>
2022-03-10 07:49:54,534:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
2022-03-10 07:49:54,778:DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
2022-03-10 07:49:54,780:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/www.onetop.n-e.kr/cert1.pem is signed by the certificate's issuer.
2022-03-10 07:49:54,781:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/www.onetop.n-e.kr/cert1.pem is: OCSPCertStatus.GOOD
2022-03-10 07:49:54,806:DEBUG:certbot._internal.display.obj:Notifying user: Certificate not yet due for renewal
2022-03-10 07:49:54,806:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1679, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1531, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 333, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 363, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 308, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 259, in _handle_identical_cert_request
    response = display_util.menu(question, choices,
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 103, in menu
    return obj.get_display().menu(message, choices, default=default, cli_flag=cli_flag,
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 131, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 397, in _get_valid_int_ans
    ans = util.input_with_timeout(input_msg)
  File "/opt/certbot/src/certbot/certbot/_internal/display/util.py", line 67, in input_with_timeout
    raise EOFError
EOFError
2022-03-10 07:49:54,807:ERROR:certbot._internal.log:An unexpected error occurred:
2022-03-10 07:49:54,808:ERROR:certbot._internal.log:EOFError
